<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AcademicCalendarController;
use App\Http\Controllers\Api\CertificateController;
use App\Http\Controllers\Api\ChatController;
use App\Http\Controllers\Api\CourseController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\EnrollmentController;
use App\Http\Controllers\Api\ExamController;
use App\Http\Controllers\Api\ForumController;
use App\Http\Controllers\Api\LessonController;
use App\Http\Controllers\Api\LgpdController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\PortalController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\ScormImportController;
use App\Http\Controllers\Api\ScormRuntimeController;
use App\Http\Controllers\Api\SettingController;
use App\Http\Controllers\Api\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/portal', [PortalController::class, 'index']);
Route::get('/portal/courses', [PortalController::class, 'courses']);
Route::get('/portal/courses/{course:slug}', [PortalController::class, 'course']);
Route::get('/certificate/validate/{code}', [CertificateController::class, 'validatePublic']);
Route::get('/lgpd/terms', [LgpdController::class, 'terms']);
Route::post('/auth/register', [AuthController::class, 'register']);
Route::post('/auth/login', [AuthController::class, 'login']);

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/auth/me', [AuthController::class, 'me']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::post('/lgpd/accept', [LgpdController::class, 'accept']);
    Route::get('/lgpd/export', [LgpdController::class, 'export']);
    Route::post('/lgpd/anonymization-request', [LgpdController::class, 'requestAnonymization']);
    Route::post('/lgpd/users/{user}/anonymize', [LgpdController::class, 'anonymizeUser']);
    Route::get('/dashboard', DashboardController::class);
    Route::get('/academic-calendar', AcademicCalendarController::class);
    Route::get('/notifications/unread-count', [NotificationController::class, 'unreadCount']);
    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::post('/notifications/mark-all-read', [NotificationController::class, 'markAllAsRead']);
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'markAsRead']);
    Route::apiResource('users', UserController::class);
    Route::get('/courses/categories', [CourseController::class, 'categories']);
    Route::apiResource('courses', CourseController::class);
    Route::apiResource('enrollments', EnrollmentController::class);
    Route::apiResource('lessons', LessonController::class);
    Route::post('/lessons/{lesson}/progress', [LessonController::class, 'progress']);
    Route::post('/scorm/import', [ScormImportController::class, 'store']);
    Route::get('/lessons/{lesson}/scorm/launch', [ScormRuntimeController::class, 'launch']);
    Route::post('/lessons/{lesson}/scorm/commit', [ScormRuntimeController::class, 'commit']);
    Route::apiResource('exams', ExamController::class);
    Route::post('/exams/{exam}/submit', [ExamController::class, 'submit']);
    Route::post('/exam-attempts/{attempt}/grade', [ExamController::class, 'gradeAttempt']);
    Route::apiResource('certificates', CertificateController::class);
    Route::post('/certificates/{certificate}/revoke', [CertificateController::class, 'revoke']);
    Route::get('/certificates/{certificate}/download', [CertificateController::class, 'download']);
    Route::get('/chats/rules', [ChatController::class, 'rules']);
    Route::apiResource('chats', ChatController::class);
    Route::post('/chats/{chat}/messages', [ChatController::class, 'message']);
    Route::apiResource('forums', ForumController::class);
    Route::get('/forum-categories', [ForumController::class, 'categories']);
    Route::get('/forum-tags', [ForumController::class, 'tags']);
    Route::get('/forum-ranking', [ForumController::class, 'ranking']);
    Route::get('/forum-notifications', [ForumController::class, 'notifications']);
    Route::get('/forum-profile/{user}', [ForumController::class, 'profile']);
    Route::get('/forum-reports', [ForumController::class, 'reports']);
    Route::post('/forums/{forum}/replies', [ForumController::class, 'reply']);
    Route::post('/forums/{forum}/react', [ForumController::class, 'react']);
    Route::post('/forums/{forum}/subscribe', [ForumController::class, 'subscribe']);
    Route::post('/forums/{forum}/report', [ForumController::class, 'report']);
    Route::post('/forums/{forum}/best-answer/{reply}', [ForumController::class, 'bestAnswer']);
    Route::post('/forum-replies/{reply}/hide', [ForumController::class, 'hideReply']);
    Route::post('/forum-warnings/{user}', [ForumController::class, 'warn']);
    Route::get('/reports', [ReportController::class, 'index']);
    Route::apiResource('settings', SettingController::class);
});
